channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=25.0
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==5.9.8
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
